version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/client-samples/java/rest"
    commit-message:
      prefix: "gradle"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
  
  - package-ecosystem: "gradle"
    directory: "/client-samples/java/websockets"
    commit-message:
      prefix: "gradle"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/client-samples/python/rest"
    commit-message:
      prefix: "pip-rest"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/client-samples/python/websockets"
    commit-message:
      prefix: "pip-websocket"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "nuget"
    directory: "/client-samples/dotnet/rest/api-template"
    commit-message:
      prefix: "nuget-rest"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "nuget"
    directory: "/client-samples/dotnet/rest/api-template.tests"
    commit-message:
      prefix: "nuget-rest-tests"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "github-actions"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
    groups:
      actions:
        patterns:
          - "actions/*"
