version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/client-samples/java/rest"
    commit-message:
      prefix: "gradle"

  - package-ecosystem: "pip"
    directory: "/client-samples/python/rest"
    commit-message:
      prefix: "pip-rest"

  - package-ecosystem: "pip"
    directory: "/client-samples/python/websockets"
    commit-message:
      prefix: "pip-websocket"

schedule:
  interval: "weekly"
  day: "monday"
  time: "08:00"