version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/client-samples/java/rest"
    commit-message:
      prefix: "gradle"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
  
  - package-ecosystem: "gradle"
    directory: "/client-samples/java/websockets"
    commit-message:
      prefix: "gradle"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/client-samples/python/rest"
    commit-message:
      prefix: "pip-rest"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"

  - package-ecosystem: "pip"
    directory: "/client-samples/python/websockets"
    commit-message:
      prefix: "pip-websocket"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
