name: .NET REST Tests

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'client-samples/dotnet/rest/**'
      - '.github/workflows/dotnet-rest-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'client-samples/dotnet/rest/**'
      - '.github/workflows/dotnet-rest-ci.yml'
jobs:
    dotnet-rest-ci:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./client-samples/dotnet/rest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        - name: Setup .NET
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: 9.0.x
        - name: Restore dependencies
          run: dotnet restore api-template && dotnet restore api-template.tests
        - name: Build
          run: dotnet build api-template --no-restore --configuration Release
        - name: Test
          run: dotnet test api-template.tests
