name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  java-checkout-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '17', '21']
        working-directory:
          - ./client-samples/java/rest/rest-okhttp
          - ./client-samples/java/rest/rest-retrofit
          - ./client-samples/java/websockets
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Gradle Build
      run: ./gradlew build
    - name: Gradle Test
      run: ./gradlew test
